name: Snyk

on:
  push:
    branches:
      - master

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
    with:
      DEBUG: true
      ORG: guardian-dotcom-n2y
      SKIP_NODE: true
    secrets:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
